template = "https://github.com/giellalt/template-lang-und"
rev_id = 88
template_sha = "63761b0f7e23e18e20ef131624577f9af069774a"

[replacements]
__REPO__ = "lang-nso"
__UND2C__ = "nso"
__UNDEFINED__ = "Pedi"
__UND__ = "nso"
