template = "https://github.com/giellalt/template-lang-und"
rev_id = 277
template_sha = "c0f383639e245d1daebce6e2006904e442eef1fd"

[replacements]
__GLOTTOLOG_ID__ = "pedi1238"
__REPO__ = "lang-nso"
__UND2C__ = "nso"
__UNDEFINED__ = "Pedi"
__UND__ = "nso"
